PK__Authenti__5E5499A83A24E32A	PRIMARY KEY	AuthenticationLogs / LogID	 <--- [PK] 	N/A (Self Primary Key)
PK__Availabi__2B1F0FB613731466	PRIMARY KEY	AvailabilityTargets.TargetID	 <--- [PK] 	N/A (Self Primary Key)
PK__Availabi__5E5499A8D9BDEC7B	PRIMARY KEY	AvailabilityLogs.LogID	 <--- [PK] 	N/A (Self Primary Key)
PK__Availabi__FBDF78C90D23DA6F	PRIMARY KEY	AvailabilityRecords.RecordID	 <--- [PK] 	N/A (Self Primary Key)
PK__Capacity__2B1F0FB6DFA21F40	PRIMARY KEY	CapacityTargets.TargetID	 <--- [PK] 	N/A (Self Primary Key)    
PK__Capacity__5E5499A8369603CB	PRIMARY KEY	CapacityLogs.LogID	 <--- [PK] 	N/A (Self Primary Key)
PK__Capacity__FBDF78C94135708F	PRIMARY KEY	CapacityRecords.RecordID	 <--- [PK] 	N/A (Self Primary Key)
PK__CashOnDe__F256EBBFFFBB764F	PRIMARY KEY	CashOnDelivery.CODID	 <--- [PK] 	N/A (Self Primary Key)
PK__ChangeAp__328477D46C5B3FDB	PRIMARY KEY	ChangeApprovals.ApprovalID	 <--- [PK] 	N/A (Self Primary Key)
PK__ChangeLo__5E5499A8DED22EBC	PRIMARY KEY	ChangeLogs.LogID	 <--- [PK] 	N/A (Self Primary Key)
PK__ChangeRe__33A8519A3141D421	PRIMARY KEY	ChangeRequests.RequestID	 <--- [PK] 	N/A (Self Primary Key)
PK__ConfigCh__0E05C5B75CA6BB9A	PRIMARY KEY	ConfigChanges.ChangeID	 <--- [PK] 	N/A (Self Primary Key)
PK__ConfigIt__C3BC333C08542607	PRIMARY KEY	ConfigItems.ConfigID	 <--- [PK] 	N/A (Self Primary Key)
PK__ConfigLo__5E5499A83A3C9C5C	PRIMARY KEY	ConfigLogs.LogID	 <--- [PK] 	N/A (Self Primary Key)
PK__Continui__5E5499A896D3F35F	PRIMARY KEY	ContinuityLogs.LogID	 <--- [PK] 	N/A (Self Primary Key)
PK__Continui__755C22D71A22CECD	PRIMARY KEY	ContinuityPlans.PlanID	 <--- [PK] 	N/A (Self Primary Key)
PK__Continui__8CC331000DFEB1A5	PRIMARY KEY	ContinuityTests.TestID	 <--- [PK] 	N/A (Self Primary Key)
PK__DigitalW__84D4F92E0B864BFD	PRIMARY KEY	DigitalWallets.WalletID	 <--- [PK] 	N/A (Self Primary Key)
PK__Forecast__4D7B4ADD5057FBEB	PRIMARY KEY	ForecastingHistory.HistoryID	 <--- [PK] 	N/A (Self Primary Key)
PK__Forecast__7F2744588F0B1B4D	PRIMARY KEY	ForecastingReports.ForecastID	 <--- [PK] 	N/A (Self Primary Key)
PK__Incident__3D80539235208CFB	PRIMARY KEY	IncidentReports.IncidentID	 <--- [PK] 	N/A (Self Primary Key)
PK__Incident__3D80539235208CFB	PRIMARY KEY	IncidentReports.IncidentID	 <--- [PK] 	N/A (Self Primary Key)
PK__Incident__516F03959377C4B8	PRIMARY KEY	IncidentTypes.TypeID	 <--- [PK] 	N/A (Self Primary Key)
PK__Invoices__D796AAD54DC75255	PRIMARY KEY	Invoices.InvoiceID	 <--- [PK] 	N/A (Self Primary Key)
PK__Merchant__8B5781BDDB87C474	PRIMARY KEY	MerchantProductMapping / MappingID	 <--- [PK] 	N/A (Self Primary Key)
PK__Merchant__8B5781BDDB87C474	PRIMARY KEY	MerchantProductMapping / MappingID	 <--- [PK] 	N/A (Self Primary Key)
PK__Merchant__8B5781BDDB87C474	PRIMARY KEY	MerchantProductMapping / MappingID	 <--- [PK] 	N/A (Self Primary Key)
PK__ProblemC__5CED516A100B1636	PRIMARY KEY	ProblemCatalog.ProblemID	 <--- [PK] 	N/A (Self Primary Key)
PK__ProblemC__5CED516A100B1636	PRIMARY KEY	ProblemCatalog.ProblemID	 <--- [PK] 	N/A (Self Primary Key)
PK__ProblemL__5E5499A80C2FFB07	PRIMARY KEY	ProblemLogs.LogID	 <--- [PK] 	N/A (Self Primary Key)
PK__ProblemL__5E5499A80C2FFB07	PRIMARY KEY	ProblemLogs.LogID	 <--- [PK] 	N/A (Self Primary Key)
PK__ProblemR__FBDF78C928604353	PRIMARY KEY	ProblemRecords.RecordID	 <--- [PK] 	N/A (Self Primary Key)
PK__ProblemR__FBDF78C928604353	PRIMARY KEY	ProblemRecords.RecordID	 <--- [PK] 	N/A (Self Primary Key)
PK__Products__B40CC6EDE88DC906	PRIMARY KEY	Products / ProductID	 <--- [PK] 	N/A (Self Primary Key)
PK__Products__B40CC6EDE88DC906	PRIMARY KEY	Products / ProductID	 <--- [PK] 	N/A (Self Primary Key)
PK__Products__B40CC6EDE88DC906	PRIMARY KEY	Products.ProductID	 <--- [PK] 	N/A (Self Primary Key)
PK__ReleaseD__5EF8D717DDB6A8F2	PRIMARY KEY	ReleaseDeployments.DeploymentID	 <--- [PK] 	N/A (Self Primary Key)
PK__ReleaseL__5E5499A89DA714FD	PRIMARY KEY	ReleaseLogs.LogID	 <--- [PK] 	N/A (Self Primary Key)
PK__Releases__5D7A69ED4C2ED9F6	PRIMARY KEY	Releases.ReleaseID	 <--- [PK] 	N/A (Self Primary Key)
PK__ReportLo__5E5499A853E0F2E6	PRIMARY KEY	ReportLogs.LogID	 <--- [PK] 	N/A (Self Primary Key)
PK__ReportRu__A259D53D21C74F0E	PRIMARY KEY	ReportRuns.RunID	 <--- [PK] 	N/A (Self Primary Key)
PK__Reports__D5BD48E528D5775C	PRIMARY KEY	Reports.ReportID	 <--- [PK] 	N/A (Self Primary Key)
PK__Shipping__5FACD460CA9BC227	PRIMARY KEY	Shipping.ShippingID	 <--- [PK] 	N/A (Self Primary Key)
PK__SupportT__712CC627E3C92A30	PRIMARY KEY	SupportTickets.TicketID	 <--- [PK] 	N/A (Self Primary Key)
PK__Taxes__711BE08C16587976	PRIMARY KEY	Taxes.TaxID	 <--- [PK] 	N/A (Self Primary Key)
PK__TicketCa__19093A2B9975A460	PRIMARY KEY	TicketCategories.CategoryID	 <--- [PK] 	N/A (Self Primary Key)
PK__TicketLo__5E5499A8EDF96B9D	PRIMARY KEY	TicketLogs.LogID	 <--- [PK] 	N/A (Self Primary Key)
PK__Transact__0D2BBCBA620D9491	PRIMARY KEY	TransactionItems / TransactionItemID	 <--- [PK] 	N/A (Self Primary Key)
PK__Transact__0D2BBCBA620D9491	PRIMARY KEY	TransactionItems / TransactionItemID	 <--- [PK] 	N/A (Self Primary Key)
PK__Transact__55433A4B7F4D0E55	PRIMARY KEY	Transactions / TransactionID	 <--- [PK] 	N/A (Self Primary Key)
PK__Transact__55433A4B7F4D0E55	PRIMARY KEY	Transactions.TransactionID	 <--- [PK] 	N/A (Self Primary Key)
PK__Users__1788CCAC8D844323	PRIMARY KEY	Users / UserID	 <--- [PK] 	N/A (Self Primary Key)
PK__Users__1788CCAC8D844323	PRIMARY KEY	Users.UserID	 <--- [PK] 	N/A (Self Primary Key)
PK__UserSess__C9F4927098B594CD	PRIMARY KEY	UserSessions / SessionID	 <--- [PK] 	N/A (Self Primary Key)
PK__UsersRol__AF27604F8FBED2C5	PRIMARY KEY	UsersRoles / RoleID	 <--- [PK] 	N/A (Self Primary Key)
PK__UsersRol__AF27604F8FBED2C5	PRIMARY KEY	UsersRoles / UserID	 <--- [PK] 	N/A (Self Primary Key)
PK__WalletTr__55433A4BC15D76F2	PRIMARY KEY	WalletTransactions.TransactionID	 <--- [PK] 	N/A (Self Primary Key)
PK_Merchants	PRIMARY KEY	Merchants / MerchantID	 <--- [PK] 	N/A (Self Primary Key)
PK_Merchants	PRIMARY KEY	Merchants / MerchantID	 <--- [PK] 	N/A (Self Primary Key)
PK_Merchants	PRIMARY KEY	Merchants.MerchantID	 <--- [PK] 	N/A (Self Primary Key)
PK_Payments	PRIMARY KEY	Payments.PaymentID	 <--- [PK] 	N/A (Self Primary Key)
				
